# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - ps: |
      if (!(Test-Path 'C:\Users\appveyor\.m2\repository\org\anarres\jarjar\jarjar-core\1.0.1-coursier-SNAPSHOT')) {
        iex 'git clone https://github.com/alexarchambault/jarjar'
        Set-Location -Path jarjar
        iex 'git checkout 249c8dbb970f8'
        iex './gradlew.bat :jarjar-core:install'
        Set-Location -Path ..
      }
build_script:
  - sbt ++2.12.1 coreJVM/publishLocal cache/publishLocal sbt-launcher/publishLocal
  - scripts/generate-sbt-launcher.sh
  - rm -rf project
  - ./csbt ++2.11.8 clean compile coreJVM/publishLocal http-server/publishLocal
  - ./csbt ++2.10.6 clean compile
  - ./csbt ++2.10.6 coreJVM/publishLocal cache/publishLocal # to make the scripted tests happy
test_script:
  - ps: Start-Job { & java -jar -noverify C:\projects\coursier\coursier launch -r http://dl.bintray.com/scalaz/releases io.get-coursier:http-server-java7_2.11:1.0.0-SNAPSHOT -- -d /C:/projects/coursier/tests/jvm/src/test/resources/test-repo/http/abc.com -u user -P pass -r realm --list-pages -v }
  - ./csbt ++2.12.1 testsJVM/test testsJVM/it:test # Would node be around for testsJS/test?
  - ./csbt ++2.11.8 testsJVM/test testsJVM/it:test
  - ./csbt ++2.10.6 testsJVM/test testsJVM/it:test sbt-coursier/scripted sbt-coursier/publishLocal sbt-shading/scripted
cache:
  - C:\Users\appveyor\.ivy2\cache
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.sbt
